#!/usr/bin/env python3
"""Sensitivity figure: MNIST-PET/CT rendering knobs and ADNI FA noise, one figure.

  python -m inpaper_utils.sens_collect

Columns: MNIST hotspot weight, MNIST PET noise sigma (inpaper_utils/sens_mnist_collect.py),
ADNI FA noise sigma (inpaper_utils/sens_adni_submit.sh). Rows: the translation into the
noisy / class-conditional modality (CT->PET, T1->FA) and back. SSIM axes start at 0.
Missing runs are left out, so it can be re-run while a grid is still training.
Figure -> snapshot_results/mnist_petct/00_inpaper_fig_sensitivity.{pdf,png};
ADNI table -> snapshot_results/adni/00_inpaper_sensitivity_table.tex; CSV -> EXPS/adni/sensitivity/.
"""
import csv
import json
import os
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
EXPS = Path(os.environ.get('MMCLAST_EXPS', '/ix/lzhan/siyuan/exps/CycleFlow'))
ADNI_NOISE = (0.0, 0.025, 0.05, 0.1)


def load(p):
    return json.loads(p.read_text()) if p.exists() else None


def adni_rows(variants):
    rows = []
    for s in ADNI_NOISE:
        refs = load(EXPS / 'adni' / 'sensitivity' / f'refs_ns{s}.json') or {}
        row = {'fa_noise': s, 'copy_t1fa_ssim': refs.get('copy T1->FA', {}).get('ssim'),
               'renoised_fa_ssim': refs.get('FA vs re-noised FA', {}).get('ssim')}
        for label, tag in variants:
            ev = load(EXPS / 'adni' / 'checkpoints' / f'sens_adni_ns{s}_{tag}' / 'paper_eval.json') or {}
            for d in ('T1->FA', 'FA->T1'):
                for m in ('ssim', 'psnr'):
                    row[f'{label} {d} {m}'] = ev.get(d, {}).get(m)
        rows.append(row)
    return rows


def main():
    sys.path.insert(0, str(ROOT))
    from inpaper_utils.sens_mnist_collect import (collect, DEFAULT, HOTSPOT, NOISE, VARIANTS, SERIES,
                                                  INK, INK2, HAIR, AXIS)
    mrows = collect()
    arows = adni_rows(VARIANTS)
    out = EXPS / 'adni' / 'sensitivity'; out.mkdir(parents=True, exist_ok=True)
    with open(out / 'sensitivity.csv', 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(arows[0])); w.writeheader(); w.writerows(arows)
    fmt = lambda v, n=4: '---' if v is None else f'{v:.{n}f}'
    lines = [r'\begin{tabular}{lcccccccc}', r'\toprule',
             r'& \multicolumn{4}{c}{$\mathrm{T1}\rightarrow\mathrm{FA}$} & \multicolumn{4}{c}{$\mathrm{FA}\rightarrow\mathrm{T1}$} \\',
             r'\cmidrule(lr){2-5}\cmidrule(lr){6-9}',
             r'& \multicolumn{2}{c}{base} & \multicolumn{2}{c}{morph-smooth} & \multicolumn{2}{c}{base} & \multicolumn{2}{c}{morph-smooth} \\',
             r'FA noise $\sigma$ & SSIM & PSNR & SSIM & PSNR & SSIM & PSNR & SSIM & PSNR \\', r'\midrule']
    for r in arows:
        cells = [fmt(r[f'{lab} {d} {m}'], 4 if m == 'ssim' else 2) for d in ('T1->FA', 'FA->T1')
                 for lab, _ in VARIANTS for m in ('ssim', 'psnr')]
        star = r'$^\ast$' if r['fa_noise'] == 0 else ''
        lines.append(f"{r['fa_noise']:g}{star} & " + ' & '.join(cells) + r' \\')
    lines += [r'\bottomrule', r'\end{tabular}']
    (ROOT / 'snapshot_results' / 'adni' / '00_inpaper_sensitivity_table.tex').write_text(
        '% Generated by inpaper_utils/sens_collect.py. $^\\ast$ = the Table 2 data, re-run through the same chain.\n'
        + '\n'.join(lines) + '\n')

    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    plt.rcParams.update({'font.family': 'serif', 'font.serif': ['STIXGeneral'], 'mathtext.fontset': 'stix',
                         'font.size': 8, 'pdf.fonttype': 42, 'ps.fonttype': 42, 'text.color': INK,
                         'axes.labelcolor': INK, 'xtick.color': INK2, 'ytick.color': INK2})
    mpts = lambda key, values, other, fixed: [next(x for x in mrows if x[key] == v and x[other] == fixed) for v in values]
    panels = [  # (title, xlabel, x values, default, points, (dir key fwd, dir key back), label fwd/back, reference key)
        ('MNIST-PET/CT', 'hotspot weight', HOTSPOT, DEFAULT[0], mpts('hotspot_weight', HOTSPOT, 'pet_noise', DEFAULT[1]),
         ('CT->PET', 'PET->CT'), 'ceiling_ct2pet_ssim'),
        ('MNIST-PET/CT', r'PET noise $\sigma$', NOISE, DEFAULT[1], mpts('pet_noise', NOISE, 'hotspot_weight', DEFAULT[0]),
         ('CT->PET', 'PET->CT'), 'ceiling_ct2pet_ssim'),
        ('ADNI', r'FA noise $\sigma$', ADNI_NOISE, 0.0, arows, ('T1->FA', 'FA->T1'), 'renoised_fa_ssim'),
    ]
    SHOW = {'base': 'Ours w/o Morph-smooth', 'morph-smooth': 'Ours w/ Morph-smooth'}  # Table 1/2 row names
    fig, axes = plt.subplots(2, 3, figsize=(5.5, 3.3), sharey=True)
    for c, (title, xlabel, values, default, pts, dirs, ref) in enumerate(panels):
        for r_, d in enumerate(dirs):
            ax = axes[r_, c]
            for label, _ in VARIANTS:
                xy = [(v, p[f'{label} {d} ssim']) for v, p in zip(values, pts) if p[f'{label} {d} ssim'] is not None]
                if xy:
                    ax.plot(*zip(*xy), marker='o', ms=3.5, lw=1.4, color=SERIES[label], label=SHOW[label])
            if r_ == 0:
                xy = [(v, p[ref]) for v, p in zip(values, pts) if p[ref] is not None]
                if xy:
                    ax.plot(*zip(*xy), ls='--', lw=1, color=INK2, label='target vs. re-noised target')
                ax.set_title(title, fontsize=8, pad=3)
            ax.text(.04, .06, d.replace('->', r'$\rightarrow$'), transform=ax.transAxes, color=INK2)
            ax.set_xticks(values, [f'{v:g}' for v in values])
            ax.set_ylim(0, 1)
            ax.axvline(default, color=HAIR, lw=.8, zorder=0)
            ax.grid(axis='y', color=HAIR, lw=.4); ax.set_axisbelow(True)
            for sp in ('top', 'right'):
                ax.spines[sp].set_visible(False)
            for sp in ('left', 'bottom'):
                ax.spines[sp].set_color(AXIS); ax.spines[sp].set_linewidth(.5)
            ax.tick_params(width=.4, length=2, labelsize=7)
            if c == 0:
                ax.set_ylabel('SSIM')
            if r_ == 1:
                ax.set_xlabel(xlabel)
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='upper center', ncol=3, frameon=False, bbox_to_anchor=(.5, 1.01))
    fig.tight_layout(rect=(0, 0, 1, .93), pad=.3, w_pad=.6)
    snap = ROOT / 'snapshot_results' / 'mnist_petct'
    for ext in ('pdf', 'png'):
        fig.savefig(snap / f'00_inpaper_fig_sensitivity.{ext}', dpi=400, facecolor='white')
    for r in arows:
        print('adni', {k: fmt(v) if isinstance(v, float) else v for k, v in r.items()})
    print('->', snap / '00_inpaper_fig_sensitivity.pdf')


if __name__ == '__main__':
    main()
