#!/usr/bin/env python3
"""Collect the MNIST-PET/CT sensitivity grid into a table and a figure.

  python -m inpaper_utils.sens_mnist_collect

Reads, per setting hw<w>_ns<s> (one knob changed from hotspot_weight 0.8, pet_noise 0.05):
  datasets/.../MNIST_CycleFlow/sensitivity/mnist_petct_paired_<setting>.refs.json  (copy floor, ceiling)
  EXPS/mnist/checkpoints/sens_<setting>_{base,morph_smooth}/paper_eval.json       (Table 2 protocol)
Missing runs are left blank, so it can be re-run while the grid is still training.
Table (LaTeX) + figure -> snapshot_results/mnist_petct/00_inpaper_{sensitivity_table.tex,
fig_sensitivity.{pdf,png}}; CSV -> EXPS/mnist/sensitivity/.
"""
import csv
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPS = Path(os.environ.get('MMCLAST_EXPS', '/ix/lzhan/siyuan/exps/CycleFlow'))
DATA = Path('/ix/lzhan/siyuan/datasets/processed_datas/MNIST_CycleFlow/sensitivity')
DEFAULT = (0.8, 0.05)
HOTSPOT = (0.0, 0.4, 0.8, 1.6)
NOISE = (0.025, 0.05, 0.1)
VARIANTS = (('base', 'base'), ('morph-smooth', 'morph_smooth'))
DIRS = ('CT->PET', 'PET->CT')
INK, INK2, HAIR, AXIS = '#0b0b0b', '#52514e', '#e1e0d9', '#c3c2b7'
SERIES = {'base': '#2a78d6', 'morph-smooth': '#e34948'}


def load(p):
    return json.loads(p.read_text()) if p.exists() else None


def setting(hw, ns):
    return f'hw{hw}_ns{ns}'


def main():
    collect(plot=True)


def collect(plot=False):
    """Rows of the MNIST grid; writes the CSV and the LaTeX table (and, if plot, the
    MNIST-only figure -- the paper figure is inpaper_utils/sens_collect.py's)."""
    rows = []
    for hw, ns in sorted({(h, DEFAULT[1]) for h in HOTSPOT} | {(DEFAULT[0], n) for n in NOISE}):
        s = setting(hw, ns)
        refs = load(DATA / f'mnist_petct_paired_{s}.refs.json') or {}
        row = {'setting': s, 'hotspot_weight': hw, 'pet_noise': ns,
               'copy_ct2pet_ssim': refs.get('copy CT->PET', {}).get('ssim'),
               'copy_pet2ct_ssim': refs.get('copy PET->CT', {}).get('ssim'),
               'ceiling_ct2pet_ssim': refs.get('ceiling CT->PET', {}).get('ssim')}
        for label, tag in VARIANTS:
            ev = load(EXPS / 'mnist' / 'checkpoints' / f'sens_{s}_{tag}' / 'paper_eval.json') or {}
            for d in DIRS:
                for metric in ('ssim', 'psnr'):
                    row[f'{label} {d} {metric}'] = ev.get(d, {}).get(metric)
        rows.append(row)

    out = EXPS / 'mnist' / 'sensitivity'
    out.mkdir(parents=True, exist_ok=True)
    with open(out / 'sensitivity.csv', 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
    fmt = lambda v, n=4: '---' if v is None else f'{v:.{n}f}'
    for r in rows:
        print(r['setting'], ' '.join(f'{k}={fmt(v)}' for k, v in r.items()
                                     if k not in ('setting', 'hotspot_weight', 'pet_noise')))

    # LaTeX: one row per setting, SSIM / PSNR per direction per variant, plus the two references.
    snap = ROOT / 'snapshot_results' / 'mnist_petct'
    lines = [r'\begin{tabular}{llcccccccc}', r'\toprule',
             r'& & \multicolumn{4}{c}{$\mathrm{CT}\rightarrow\mathrm{PET}$} & \multicolumn{4}{c}{$\mathrm{PET}\rightarrow\mathrm{CT}$} \\',
             r'\cmidrule(lr){3-6}\cmidrule(lr){7-10}',
             r'& & \multicolumn{2}{c}{base} & \multicolumn{2}{c}{morph-smooth} & \multicolumn{2}{c}{base} & \multicolumn{2}{c}{morph-smooth} \\',
             r'Knob & Value & SSIM & PSNR & SSIM & PSNR & SSIM & PSNR & SSIM & PSNR \\', r'\midrule']
    for knob, key, values in (('hotspot', 'hotspot_weight', HOTSPOT), ('noise $\\sigma$', 'pet_noise', NOISE)):
        for v in values:
            r = next(x for x in rows if x[key] == v and (x['pet_noise'] if key == 'hotspot_weight' else x['hotspot_weight'])
                     == (DEFAULT[1] if key == 'hotspot_weight' else DEFAULT[0]))
            cells = [fmt(r[f'{lab} {d} {m}'], 4 if m == 'ssim' else 2) for d in DIRS for lab, _ in VARIANTS
                     for m in ('ssim', 'psnr')]
            mark = r'$^\ast$' if (r['hotspot_weight'], r['pet_noise']) == DEFAULT else ''
            lines.append(f'{knob} & {v}{mark} & ' + ' & '.join(cells) + r' \\')
        lines.append(r'\midrule' if key == 'hotspot_weight' else r'\bottomrule')
    lines.append(r'\end{tabular}')
    (snap / '00_inpaper_sensitivity_table.tex').write_text(
        '% Generated by inpaper_utils/sens_mnist_collect.py. $^\\ast$ = the Table 2 build, re-run through\n'
        '% the same chain as the other settings.\n' + '\n'.join(lines) + '\n')
    if not plot:
        return rows

    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    plt.rcParams.update({'font.family': 'serif', 'font.serif': ['STIXGeneral'], 'mathtext.fontset': 'stix',
                         'font.size': 8, 'pdf.fonttype': 42, 'ps.fonttype': 42, 'text.color': INK,
                         'axes.labelcolor': INK, 'xtick.color': INK2, 'ytick.color': INK2})
    # The copy floor (~0.46) is left to the table: drawn, it squeezes every curve into
    # the top tenth of the axis. The dashed line is SSIM between two noise draws of the
    # same PET -- a bound for samplers that reproduce the noise, not for a model that
    # predicts the noise-free mean, which can and does score above it.
    fig, axes = plt.subplots(2, 2, figsize=(5.5, 3.4), sharey='row')
    for c, (key, values, xlabel, other, fixed) in enumerate(
            (('hotspot_weight', HOTSPOT, 'hotspot weight', 'pet_noise', DEFAULT[1]),
             ('pet_noise', NOISE, r'PET noise $\sigma$', 'hotspot_weight', DEFAULT[0]))):
        pts = [next(x for x in rows if x[key] == v and x[other] == fixed) for v in values]
        for r_, d in enumerate(DIRS):
            ax = axes[r_, c]
            for label, _ in VARIANTS:
                ys = [p[f'{label} {d} ssim'] for p in pts]
                xy = [(v, y) for v, y in zip(values, ys) if y is not None]
                if xy:
                    ax.plot(*zip(*xy), marker='o', ms=4, lw=1.5, color=SERIES[label], label=label)
            if d == 'CT->PET':
                xy = [(v, p['ceiling_ct2pet_ssim']) for v, p in zip(values, pts) if p['ceiling_ct2pet_ssim'] is not None]
                if xy:
                    ax.plot(*zip(*xy), ls='--', lw=1, color=INK2, label='PET vs. re-noised PET')
            ax.set_xticks(values, [f'{v:g}' for v in values])
            ax.set_ylim(0, 1)
            ax.axvline(DEFAULT[c == 1], color=HAIR, lw=.8, zorder=0)
            ax.grid(axis='y', color=HAIR, lw=.4); ax.set_axisbelow(True)
            for sp in ('top', 'right'):
                ax.spines[sp].set_visible(False)
            for sp in ('left', 'bottom'):
                ax.spines[sp].set_color(AXIS); ax.spines[sp].set_linewidth(.5)
            ax.tick_params(width=.4, length=2)
            if c == 0:
                ax.set_ylabel(f'SSIM, {d.replace("->", " → ")}')
            if r_ == 1:
                ax.set_xlabel(xlabel)
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='upper center', ncol=4, frameon=False, bbox_to_anchor=(.5, 1.02))
    fig.tight_layout(rect=(0, 0, 1, .94), pad=.3)
    for ext in ('pdf', 'png'):
        fig.savefig(snap / f'00_inpaper_fig_sensitivity_mnist_only.{ext}', dpi=400, facecolor='white')
    print('->', snap / '00_inpaper_sensitivity_table.tex', snap / '00_inpaper_fig_sensitivity_mnist_only.pdf',
          out / 'sensitivity.csv')
    return rows


if __name__ == '__main__':
    main()
